version: "3.9"
services:
  spark:
    image: bitnami/spark:3.3.3
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_LOCAL_IP=spark
    ports:
      - 7077:7077
      - 8080:8080
    networks:
      - etl-net

  worker:
    image: bitnami/spark:3.3.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    depends_on:
      - spark
    networks:
      - etl-net

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=warehouse
    ports:
      - 5432:5432
    networks:
      - etl-net

  etl:
    build: .
    volumes:
      - ./data:/opt/data
    depends_on:
      - spark
      - db
    networks:
      - etl-net

networks:
  etl-net:
    driver: bridge